// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Bloom = "Bloom",
  FairyLights = "FairyLights",
  FairyLights_1_High_glb = "FairyLights_1_High.glb",
  FairyLights_1_Low_glb = "FairyLights_1_Low.glb",
  FairyLights_1_Mid_glb = "FairyLights_1_Mid.glb",
  FairyLights_2_High_glb = "FairyLights_2_High.glb",
  FairyLights_2_Low_glb = "FairyLights_2_Low.glb",
  FairyLights_2_Mid_glb = "FairyLights_2_Mid.glb",
  Image = "Image",
  Image_2 = "Image_2",
  Image_3 = "Image_3",
  Image_4 = "Image_4",
  Image_5 = "Image_5",
  Image_6 = "Image_6",
  Image_7 = "Image_7",
  Image_8 = "Image_8",
  Image_9 = "Image_9",
  InteractivePlants = "InteractivePlants",
  Petal = "Petal",
  Plant_1 = "Plant_1",
  Plant_10 = "Plant_10",
  Plant_11 = "Plant_11",
  Plant_12 = "Plant_12",
  Plant_13 = "Plant_13",
  Plant_14 = "Plant_14",
  Plant_15 = "Plant_15",
  Plant_16 = "Plant_16",
  Plant_17 = "Plant_17",
  Plant_18 = "Plant_18",
  Plant_19 = "Plant_19",
  Plant_2 = "Plant_2",
  Plant_20 = "Plant_20",
  Plant_21 = "Plant_21",
  Plant_22 = "Plant_22",
  Plant_3 = "Plant_3",
  Plant_4 = "Plant_4",
  Plant_5 = "Plant_5",
  Plant_6 = "Plant_6",
  Plant_7 = "Plant_7",
  Plant_8 = "Plant_8",
  Plant_9 = "Plant_9",
  Sit_Spot_1 = "Sit Spot_1",
  Sit_Spot_10 = "Sit Spot_10",
  Sit_Spot_11 = "Sit Spot_11",
  Sit_Spot_12 = "Sit Spot_12",
  Sit_Spot_2 = "Sit Spot_2",
  Sit_Spot_3 = "Sit Spot_3",
  Sit_Spot_4 = "Sit Spot_4",
  Sit_Spot_5 = "Sit Spot_5",
  Sit_Spot_6 = "Sit Spot_6",
  Sit_Spot_7 = "Sit Spot_7",
  Sit_Spot_8 = "Sit Spot_8",
  Sit_Spot_9 = "Sit Spot_9",
  Spotlight = "Spotlight",
  TrellisLights_1_High_glb = "TrellisLights_1_High.glb",
  TrellisLights_1_Low_glb = "TrellisLights_1_Low.glb",
  TrellisLights_1_Mid_glb = "TrellisLights_1_Mid.glb",
  TrellisLights_2_High_glb = "TrellisLights_2_High.glb",
  TrellisLights_2_Low_glb = "TrellisLights_2_Low.glb",
  TrellisLights_2_Mid_glb = "TrellisLights_2_Mid.glb",
  centerTextBloom = "centerTextBloom",
  centerTextProgress = "centerTextProgress",
  lamppost_glb = "lamppost.glb",
  lamppost_glb_2 = "lamppost.glb_2",
  lamppost_glb_3 = "lamppost.glb_3",
  lamppost_glb_4 = "lamppost.glb_4",
  scene_glb = "scene.glb",
  wateringLabel1 = "wateringLabel1",
  wateringLabel2 = "wateringLabel2",
  wateringLabel3 = "wateringLabel3",
  wateringLabel4 = "wateringLabel4",
} 
