// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Bloom = "Bloom",
  Ground = "Ground",
  Image = "Image",
  Image_2 = "Image_2",
  Image_3 = "Image_3",
  Image_4 = "Image_4",
  Image_5 = "Image_5",
  Image_6 = "Image_6",
  Image_7 = "Image_7",
  Image_8 = "Image_8",
  Image_9 = "Image_9",
  InteractivePlants = "InteractivePlants",
  Leaderboard_1 = "Leaderboard_1",
  Leaderboard_2 = "Leaderboard_2",
  Petal = "Petal",
  Plant_1 = "Plant_1",
  Plant_10 = "Plant_10",
  Plant_11 = "Plant_11",
  Plant_12 = "Plant_12",
  Plant_13 = "Plant_13",
  Plant_14 = "Plant_14",
  Plant_15 = "Plant_15",
  Plant_16 = "Plant_16",
  Plant_17 = "Plant_17",
  Plant_18 = "Plant_18",
  Plant_19 = "Plant_19",
  Plant_2 = "Plant_2",
  Plant_20 = "Plant_20",
  Plant_21 = "Plant_21",
  Plant_22 = "Plant_22",
  Plant_3 = "Plant_3",
  Plant_4 = "Plant_4",
  Plant_5 = "Plant_5",
  Plant_6 = "Plant_6",
  Plant_7 = "Plant_7",
  Plant_8 = "Plant_8",
  Plant_9 = "Plant_9",
  Tile_1 = "Tile 1",
  Tile_2 = "Tile 2",
  Tile_3 = "Tile 3",
  center = "center",
  centerTextBloom = "centerTextBloom",
  centerTextProgress = "centerTextProgress",
  centerToon = "centerToon",
  scene_glb = "scene.glb",
  wateringLabel1 = "wateringLabel1",
  wateringLabel2 = "wateringLabel2",
  wateringLabel3 = "wateringLabel3",
  wateringLabel4 = "wateringLabel4",
} 
